spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GongGan
    username: root
    password: root!

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true